version: "3.7"

services:
  app:
    build: ./EquilibriumCore/
    restart: always
    networks:
      - web
      - default
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=equilibrium.jupotter.eu
      - LETSENCRYPT_EMAIL=webmaster@jupotter.eu
      - LETSENCRYPT_HOST=equilibrium.jupotter.eu
      - ASPNETCORE_ENVIRONMENT=Production
    labels:
      - "traefik.http.routers.equilibrium-secure.rule=host(`equilibrium.jupotter.eu`)"
      - "traefik.http.routers.equilibrium-secure.entrypoints=https"
      - "traefik.http.routers.equilibrium-secure.tls.certresolver=default"
      - "traefik.http.services.app-equilibrium.loadbalancer.server.port=80"
      - "traefik.enable=true"

  db:
    image: mariadb
    restart: always
    networks:
      - adminer
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=ange19061991
      - MYSQL_DATABASE=EquilibriumBD
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  web:
    external: true
  adminer:
    external: true
