version: "3.7"

services:
  app:
    build: ./EquilibriumCore/
    networks:
      - web
      - default
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=equilibrium.jupotter.eu
      - LETSENCRYPT_EMAIL=webmaster@jupotter.eu
      - LETSENCRYPT_HOST=equilibrium.jupotter.eu
      - ASPNETCORE_ENVIRONMENT=Production
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.backend=EquilibriumNet"
      - "traefik.frontend.rule=Host:equilibrium.jupotter.eu"
      - "traefik.port=80"

  db:
    image: mariadb
    networks:
      - adminer
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=ange19061991
      - MYSQL_DATABASE=EquilibriumBD
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  web:
    external: true
  adminer:
    external: true
