// <auto-generated />
namespace EquilibriumNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removefocusandaddskills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removefocusandaddskills));
        
        string IMigrationMetadata.Id
        {
            get { return "201908011407063_remove focus and add skills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
